// frontend/src/pages/home/components/sponsors/sponsors.tsx
import { Avatar, Box, Group, Marquee, Paper, Text } from '@mantine/core';
import { useQuery } from '@tanstack/react-query';
import { api } from '@/api';

import type { SponsorResource } from './types';
import { SPONSOR_COLLECTION_ID } from './constants';

export function Sponsors() {
  const { data: sponsors } = useQuery<SponsorResource[]>({
    queryKey: ['sponsors'],
    queryFn: () => {
      return api.request({
        url: '/resource',
        query: { collectionId: SPONSOR_COLLECTION_ID },
      });
    },
  });

  if (!sponsors?.length) return null;

  return (
    <Box
      style={{
        width: '100vw',
        marginLeft: 'calc(50% - 50vw)',
      }}
    >
      <Marquee
        fadeEdges
        fadeEdgeColor='var(--bg-gray)'
        gap='md'
        duration={40000}
        pauseOnHover
        styles={{ root: { padding: '8px 0' } }}
      >
        {sponsors.map((sponsor) => (
          <Paper
            key={sponsor.id}
            py='8px'
            px='md'
            bg='var(--card-bg)'
            withBorder
            style={{
              width: '300px',
              height: '64px',
              borderColor: 'var(--card-border)',
              position: 'relative',
            }}
          >
            <Group gap='12px' wrap='nowrap' h='100%' align='center'>
              <Avatar
                radius='sm'
                size='md'
                name={sponsor.payload.name}
                src={sponsor.payload.logo}
                styles={{
                  image: { objectFit: 'contain' },
                }}
              />
              <div style={{ minWidth: 0, flex: 1 }}>
                <Text size='sm' fw='600' truncate lh='1.2'>
                  {sponsor.payload.name}
                </Text>
                {sponsor.payload.year && (
                  <Text size='xs' c='primary' lh='1.2'>
                    {sponsor.payload.year}
                  </Text>
                )}
              </div>
            </Group>
          </Paper>
        ))}
      </Marquee>
    </Box>
  );
}

// frontend/src/components/Sponsors/Sponsors.vue
<script setup lang="ts">
import Avatar from 'primevue/avatar';
import { CmsRequests, type SponsorResource } from '@/services/requests/CmsRequests';

/*---------------------------------------------
/  PROPS & EMITS
---------------------------------------------*/
/*---------------------------------------------
/  VARIABLES
---------------------------------------------*/
const { data: sponsors } = useQuery<SponsorResource[]>({
  key: ['sponsors'],
  request: () => CmsRequests.sponsors(),
});
/*---------------------------------------------
/  HOOKS
---------------------------------------------*/
</script>

<template>
  <div v-if="sponsors?.length" class="sponsors">
    <div
      v-for="sponsor in sponsors"
      :key="sponsor.id"
      class="sponsors__card"
    >
      <Avatar
        :image="sponsor.payload.logo"
        :label="sponsor.payload.name?.[0]"
        shape="square"
        size="large"
      />
      <div class="sponsors__meta">
        <div class="sponsors__name">{{ sponsor.payload.name }}</div>
        <div v-if="sponsor.payload.year" class="sponsors__year">
          {{ sponsor.payload.year }}
        </div>
      </div>
    </div>
  </div>
</template>

<style lang="scss" scoped>
.sponsors {
  display: flex;
  flex-wrap: wrap;
  gap: 16px;
  justify-content: center;

  &__card {
    display: flex;
    align-items: center;
    gap: 12px;
    width: 300px;
    padding: 8px 16px;
    background: var(--card-bg);
    border: 1px solid var(--card-border);
    border-radius: 4px;
  }

  &__meta {
    min-width: 0;
    flex: 1;
  }

  &__name {
    font-size: 14px;
    font-weight: 600;
    line-height: 1.2;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
  }

  &__year {
    font-size: 12px;
    color: var(--color-primary);
    line-height: 1.2;
  }
}
</style>
