// frontend-vue/src/components/Mentors/Mentors.vue
<script setup lang="ts">
import Avatar from 'primevue/avatar';
import { CmsRequests, type MentorResource } from '@/services/requests/CmsRequests';

/*---------------------------------------------
/  PROPS & EMITS
---------------------------------------------*/
/*---------------------------------------------
/  VARIABLES
---------------------------------------------*/
const { data: mentors } = useQuery<MentorResource[]>({
  key: ['mentors'],
  request: () => CmsRequests.mentors(),
});
/*---------------------------------------------
/  METHODS
---------------------------------------------*/
const photoFor = (m: MentorResource) =>
  m.payload.photo ?? m.objects?.find((o) => o.key === 'photo')?.url ?? undefined;

const initials = (name: string) =>
  name
    .trim()
    .split(/\s+/)
    .slice(0, 2)
    .map((p) => p[0]?.toUpperCase() ?? '')
    .join('');
/*---------------------------------------------
/  HOOKS
---------------------------------------------*/
</script>

<template>
  <div class="mentors">
    <div v-for="mentor in mentors ?? []" :key="mentor.id" class="mentors__card">
      <Avatar
        :image="photoFor(mentor)"
        :label="initials(mentor.payload.name)"
        shape="circle"
        size="xlarge"
      />
      <div class="mentors__name">{{ mentor.payload.name }}</div>
      <a :href="`mailto:${mentor.payload.email}`" class="mentors__email">
        {{ mentor.payload.email }}
      </a>
    </div>
  </div>
</template>

<style lang="scss" scoped>
@import 'breakpoints';

.mentors {
  display: flex;
  flex-wrap: wrap;
  gap: 16px;
  justify-content: center;

  &__card {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 8px;
    padding: 20px;
    width: 280px;
    background: var(--card-bg);
    border: 1px solid var(--card-border);
    border-radius: 8px;

    @include media-down(sm) {
      width: 100%;
    }
  }

  &__name {
    font-size: 15px;
    font-weight: 600;
    text-align: center;
    line-height: 1.2;
  }

  &__email {
    font-size: 12px;
    color: var(--color-dimmed);
    text-decoration: none;
    word-break: break-all;
    text-align: center;

    &:hover {
      color: var(--color-primary);
    }
  }
}
</style>

// frontend/src/pages/home/components/mentors/mentors.tsx
import { useQuery } from '@tanstack/react-query';
import { Anchor, Avatar, Card, Flex, Stack, Text } from '@mantine/core';
import { motion } from 'motion/react';

import { api } from '@/api';

import { MENTOR_COLLECTION_ID } from './constants';
import type { MentorResource } from './types';
import classes from './mentors.module.css';

export function Mentors() {
  const { data: mentors } = useQuery<MentorResource[]>({
    queryKey: ['mentors'],
    queryFn: () => {
      return api.request({
        url: '/resource',
        query: { collectionId: MENTOR_COLLECTION_ID },
      });
    },
  });

  return (
    <Flex gap='md' justify='center' wrap='wrap'>
      {mentors?.map((mentor, idx) => {
        const photo =
          mentor.payload.photo ??
          mentor.objects?.find((o) => o.key === 'photo')?.url;
        return (
          <motion.div
            key={mentor.id}
            className={classes.cardWrap}
            initial={{ opacity: 0, y: 24, scale: 0.94 }}
            whileInView={{ opacity: 1, y: 0, scale: 1 }}
            viewport={{ once: true, amount: 0.2 }}
            transition={{
              duration: 0.45,
              delay: idx * 0.07,
              ease: [0.22, 1, 0.36, 1],
            }}
            whileHover={{ y: -6, transition: { duration: 0.2 } }}
          >
            <Card
              padding='lg'
              radius='md'
              bg='var(--card-bg)'
              w={{ base: '100%', xs: '280px' }}
              miw={{ base: '100%', xs: '280px' }}
              h={{ base: 'auto', xs: '260px' }}
              mih={{ base: '180px', xs: '260px' }}
              style={{ border: '1px solid var(--card-border)' }}
            >
              <Stack align='center' gap='sm' justify='center' h='100%'>
                <Avatar
                  src={photo}
                  name={mentor.payload.name}
                  size={72}
                  radius='50%'
                  color='primary'
                />
                <Stack gap={2} align='center'>
                  <Text fz={{ base: '14px', sm: '15px' }} fw='600' ta='center' lh='1.2' lineClamp={2}>
                    {mentor.payload.name}
                  </Text>
                  <Anchor
                    href={`mailto:${mentor.payload.email}`}
                    fz='12px'
                    c='dimmed'
                    ta='center'
                    style={{ wordBreak: 'break-all' }}
                  >
                    {mentor.payload.email}
                  </Anchor>
                </Stack>
              </Stack>
            </Card>
          </motion.div>
        );
      })}
    </Flex>
  );
}
