// frontend/src/pages/home/components/hero.tsx
import {
  Title,
  Text,
  Box,
  Flex,
  Paper,
  Stack,
  Group,
  ThemeIcon,
  Divider,
} from '@mantine/core';
import {
  LuArrowUpFromLine,
  LuDiameter,
  LuMoveVertical,
  LuWeight,
} from 'react-icons/lu';
import { motion } from 'motion/react';

import { Container } from '@/components/container';
import { useTranslation, type TranslationKey } from '@/i18n';

import classes from './hero.module.css';

const ROCKET_INFO: {
  labelKey: TranslationKey;
  value: string;
  icon: typeof LuMoveVertical;
}[] = [
  { labelKey: 'rocket.height', value: '95 cm', icon: LuMoveVertical },
  { labelKey: 'rocket.diameter', value: '7.65 cm', icon: LuDiameter },
  { labelKey: 'rocket.thrust', value: '700 N', icon: LuArrowUpFromLine },
  { labelKey: 'rocket.mass', value: '3.5 kg', icon: LuWeight },
];

const TITLE_LINES = [
  'Escape',
  'Velocity',
  'Rocketry',
  'Student',
  'Team',
] as const;

export function Hero() {
  const { t } = useTranslation();

  return (
    <Box w='100%' h='100vh' p={{ base: 'sm', sm: 'xl' }}>
      <Container h='100%'>
        <Flex
          h='100%'
          align={{ base: 'flex-start', md: 'center' }}
          justify='space-between'
          gap='xl'
          direction={{ base: 'column', md: 'row' }}
          pt={{ base: '80px', md: 0 }}
        >
          <Box
            className={classes.titleColumn}
          >
            <Title
              order={1}
              c='primary'
              tt='uppercase'
              lh='1.16'
              style={{
                display: 'flex',
                flexDirection: 'column',
                alignItems: 'start',
                fontSize: 'clamp(1.125rem, 5.5vw, 3rem)',
              }}
            >
              {TITLE_LINES.map((word, i) => (
                <motion.span
                  key={word}
                  initial={{ opacity: 0, y: 12 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{
                    duration: 0.4,
                    delay: i * 0.06,
                    ease: [0.22, 1, 0.36, 1],
                  }}
                  style={{ paddingRight: 'var(--mantine-spacing-md)' }}
                >
                  {word}
                </motion.span>
              ))}
            </Title>
          </Box>

          <Box
            style={{
              flexBasis: '40%',
              minWidth: 0,
              width: '100%',
              maxWidth: '420px',
            }}
            visibleFrom='md'
          >
            <Stack gap='sm'>
              {ROCKET_INFO.map((item, i) => {
                const Icon = item.icon;

                return (
                  <motion.div
                    key={item.labelKey}
                    initial={{ opacity: 0, x: 16 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{
                      duration: 0.4,
                      delay: 0.15 + i * 0.06,
                      ease: [0.22, 1, 0.36, 1],
                    }}
                  >
                    <Group align='center' gap='sm'>
                      <Divider style={{ flexGrow: 1 }} />
                      <Paper
                        w='160px'
                        py='sm'
                        bg='var(--card-bg)'
                        style={{ borderColor: 'var(--card-border)' }}
                        withBorder
                      >
                        <Flex justify='center'>
                          <Group gap='xs'>
                            <ThemeIcon variant='transparent'>
                              <Icon
                                color='var(--mantine-primary-color-filled)'
                                size='calc(var(--mantine-font-size-xl) * 1.25)'
                              />
                            </ThemeIcon>
                            <div>
                              <Text fw='500'>{item.value}</Text>
                              <Text c='dimmed' size='xs' tt='uppercase'>
                                {t(item.labelKey)}
                              </Text>
                            </div>
                          </Group>
                        </Flex>
                      </Paper>
                    </Group>
                  </motion.div>
                );
              })}
            </Stack>
          </Box>
        </Flex>
      </Container>
    </Box>
  );
}

// frontend/src/components/Hero/Hero.vue
<script setup lang="ts">
import { motion } from 'motion-v';

/*---------------------------------------------
/  PROPS & EMITS
---------------------------------------------*/
/*---------------------------------------------
/  VARIABLES
---------------------------------------------*/
const { t } = useI18n();

const titleLines = ['Escape', 'Velocity', 'Rocketry', 'Student', 'Team'];

const rocketInfo = [
  { labelKey: 'rocket.height', value: '95 cm' },
  { labelKey: 'rocket.diameter', value: '7.65 cm' },
  { labelKey: 'rocket.thrust', value: '700 N' },
  { labelKey: 'rocket.mass', value: '3.5 kg' },
];

const ease: [number, number, number, number] = [0.22, 1, 0.36, 1];
/*---------------------------------------------
/  METHODS
---------------------------------------------*/
/*---------------------------------------------
/  COMPUTED
---------------------------------------------*/
/*---------------------------------------------
/  WATCHERS
---------------------------------------------*/
/*---------------------------------------------
/  HOOKS
---------------------------------------------*/
</script>

<template>
  <section class="relative z-10 w-full h-100vh p-16px sm:p-32px">
    <div
      class="container flex flex-col items-start justify-between gap-32px h-full pt-80px md:(flex-row items-center pt-0)"
    >
      <div class="w-full md:flex-[0_0_50%]">
        <h1
          class="m-0 flex flex-col items-start uppercase text-primary fs-[clamp(1.125rem,5.5vw,3rem)] lh-[1.16] font-[var(--font-family-headline)]"
        >
          <motion.span
            v-for="(word, i) in titleLines"
            :key="word"
            class="pr-16px"
            :initial="{ opacity: 0, y: 12 }"
            :animate="{ opacity: 1, y: 0 }"
            :transition="{ duration: 0.4, delay: i * 0.06, ease }"
          >
            {{ word }}
          </motion.span>
        </h1>
      </div>

      <div
        class="hidden md:flex w-full max-w-420px flex-col gap-12px md:flex-basis-[40%]"
      >
        <motion.div
          v-for="(item, i) in rocketInfo"
          :key="item.labelKey"
          class="flex items-center gap-12px"
          :initial="{ opacity: 0, x: 16 }"
          :animate="{ opacity: 1, x: 0 }"
          :transition="{ duration: 0.4, delay: 0.15 + i * 0.06, ease }"
        >
          <hr class="flex-grow border-0 border-t border-cardBorder" />
          <div
            class="w-160px py-12px px-16px border border-cardBorder rounded-4px bg-cardBg text-center"
          >
            <div class="font-500 fs-16px">{{ item.value }}</div>
            <div class="text-[var(--color-dimmed)] fs-12px uppercase">
              {{ t(item.labelKey) }}
            </div>
          </div>
        </motion.div>
      </div>
    </div>
  </section>
</template>

<style lang="scss" scoped></style>
