// frontend/src/components/Header/Header.vue
<script setup lang="ts">
import Drawer from 'primevue/drawer';
import SelectButton from 'primevue/selectbutton';
import type { Language } from '@/translations';

/*---------------------------------------------
/  PROPS & EMITS
---------------------------------------------*/
/*---------------------------------------------
/  VARIABLES
---------------------------------------------*/
const { t } = useI18n();
const { locale, setLocale } = useLocale();
const scrolled = ref(false);
const drawerOpen = ref(false);

const localeOptions = [
  { label: 'EN', value: 'en' },
  { label: 'HU', value: 'hu' },
];

const menuItems = computed(() => [
  { label: t('nav.events'), to: '/#events' },
  { label: t('nav.about'), to: '/#about' },
  { label: t('nav.team'), to: '/#team' },
  { label: t('nav.mentors'), to: '/#mentors' },
  { label: t('nav.sponsors'), to: '/#sponsors' },
  { label: t('nav.joinUs'), to: '/join-us' },
]);

const localeModel = computed({
  get: () => locale.value,
  set: (val: string) => setLocale(val as Language),
});

/*---------------------------------------------
/  METHODS
---------------------------------------------*/
const onScroll = () => {
  scrolled.value = window.scrollY > 8;
};

const closeDrawer = () => {
  drawerOpen.value = false;
};

/*---------------------------------------------
/  HOOKS
---------------------------------------------*/
onMounted(() => {
  onScroll();
  window.addEventListener('scroll', onScroll, { passive: true });
});

onBeforeUnmount(() => {
  window.removeEventListener('scroll', onScroll);
});
</script>

<template>
  <header class="header" :class="{ scrolled }">
    <div class="container header__inner">
      <div class="header__col header__col--logo">
        <span class="header__logo-wrap">
          <EvrstLogo :height="scrolled ? '36px' : '80px'" />
        </span>
      </div>

      <div class="header__col header__col--center">
        <nav class="header__nav">
          <RouterLink v-for="item in menuItems" :key="item.to" :to="item.to" class="header__link">
            {{ item.label }}
          </RouterLink>
        </nav>
      </div>

      <div class="header__col header__col--end">
        <div class="header__locale">
          <SelectButton
            v-model="localeModel"
            :options="localeOptions"
            option-label="label"
            option-value="value"
            :allow-empty="false"
            size="small"
          />
        </div>
        <button
          type="button"
          class="header__burger"
          aria-label="Toggle navigation"
          @click="drawerOpen = true"
        >
          <span></span>
          <span></span>
          <span></span>
        </button>
      </div>
    </div>

    <Drawer v-model:visible="drawerOpen" position="right" class="header__drawer">
      <nav class="header__drawer-nav">
        <RouterLink
          v-for="item in menuItems"
          :key="item.to"
          :to="item.to"
          class="header__drawer-link"
          @click="closeDrawer"
        >
          {{ item.label }}
        </RouterLink>
      </nav>
      <div class="mt-24px">
        <SelectButton
          v-model="localeModel"
          :options="localeOptions"
          option-label="label"
          option-value="value"
          :allow-empty="false"
          size="small"
        />
      </div>
    </Drawer>
  </header>
</template>

<style lang="scss" scoped>
@import 'breakpoints';

.header {
  position: fixed;
  top: 0;
  right: 0;
  left: 0;
  border-bottom: 1px solid transparent;
  background-color: transparent;
  transition: background-color 200ms ease, backdrop-filter 200ms ease, border-color 200ms ease;
  z-index: 100;

  &.scrolled {
    background-color: rgb(20 21 23 / 60%);
    backdrop-filter: blur(12px);
    backdrop-filter: blur(12px);
    border-bottom-color: var(--card-border);

    .header__inner {
      padding-top: 8px;
      padding-bottom: 8px;
    }
  }

  &__inner {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 16px;
    padding-top: 16px;
    padding-bottom: 16px;
    transition: padding 200ms ease;
  }

  &__col {
    flex: 1 1 0;
    display: flex;
    align-items: center;

    &--logo {
      justify-content: flex-start;
      position: relative;
    }

    &--center {
      justify-content: center;

      @include media-down(md) {
        display: none;
      }
    }

    &--end {
      justify-content: flex-end;
      gap: 12px;
    }
  }

  &__logo-wrap {
    display: inline-flex;

    :deep(img) {
      margin-bottom: -40px;

      @include media-down(sm) {
        height: 56px !important;
        margin-bottom: -28px;
      }
    }
  }

  &.scrolled &__logo-wrap :deep(img) {
    margin-bottom: 0;

    @include media-down(sm) {
      height: 28px !important;
    }
  }

  &__nav {
    display: flex;
    gap: 32px;
    text-transform: uppercase;
    white-space: nowrap;
  }

  &__link {
    color: white;
    font-size: 14px;
    text-decoration: none;
    transition: color 150ms ease;

    &:hover {
      color: var(--color-primary);
    }
  }

  &__locale {
    @include media-down(md) {
      display: none;
    }
  }

  &__burger {
    display: none;
    justify-content: space-around;
    width: 32px;
    height: 32px;
    padding: 6px;
    border: none;
    background: transparent;
    flex-direction: column;
    cursor: pointer;

    @include media-down(md) {
      display: flex;
    }

    span {
      display: block;
      width: 100%;
      height: 2px;
      background-color: white;
    }
  }

  &__drawer-nav {
    display: flex;
    flex-direction: column;
    gap: 16px;
  }

  &__drawer-link {
    color: white;
    font-weight: 500;
    font-size: 18px;
    text-transform: uppercase;
    text-decoration: none;
  }
}
</style>

// frontend/src/components/header/header.tsx
import { useEffect, useState } from 'react';
import { Link } from 'react-router';
import {
  Anchor,
  Box,
  Burger,
  Drawer,
  Flex,
  Group,
  SegmentedControl,
  Stack,
} from '@mantine/core';
import { useDisclosure } from '@mantine/hooks';

import { MENU_ITEMS } from '@/constants';
import { Container } from '@/components/container';
import { EvrstLogo } from '@/components/evrst-logo';
import { useTranslation, type Language } from '@/i18n';

import classes from './header.module.css';

interface HeaderProps {
  withNavigation?: boolean;
}

export function Header(props: HeaderProps) {
  const { withNavigation = true } = props;
  const { language, setLanguage, t } = useTranslation();
  const [scrolled, setScrolled] = useState(false);
  const [drawerOpen, { open: openDrawer, close: closeDrawer }] =
    useDisclosure(false);

  useEffect(() => {
    const onScroll = () => setScrolled(window.scrollY > 8);
    onScroll();
    window.addEventListener('scroll', onScroll, { passive: true });
    return () => window.removeEventListener('scroll', onScroll);
  }, []);

  const className = [classes.root, scrolled && classes.scrolled]
    .filter(Boolean)
    .join(' ');

  const languageSwitch = (
    <SegmentedControl
      value={language}
      onChange={(value) => setLanguage(value as Language)}
      data={[
        { value: 'en', label: 'EN' },
        { value: 'hu', label: 'HU' },
      ]}
      styles={{
        root: { height: '32px', minHeight: '32px' },
        label: {
          paddingTop: 0,
          paddingBottom: 0,
          height: '28px',
          display: 'flex',
          alignItems: 'center',
          fontSize: '12px',
        },
        indicator: { height: '28px' },
      }}
    />
  );

  return (
    <header className={className}>
      <Container className={classes.inner}>
        <Flex justify='space-between' align='center' gap='md'>
          <Box
            className={`${classes.column} ${classes.logoColumn}`}
            style={{ justifyContent: 'flex-start' }}
          >
            <span className={classes.logoWrap}>
              <EvrstLogo />
            </span>
          </Box>

          <Box
            className={classes.column}
            style={{ justifyContent: 'center' }}
            visibleFrom='md'
          >
            {withNavigation && (
              <Group component='nav' tt='uppercase' wrap='nowrap' gap='xl'>
                {MENU_ITEMS.map((item) => (
                  <Anchor
                    key={item.labelKey}
                    component={Link}
                    to={item.url}
                    underline='hover'
                    c='white'
                    className={classes.navLink}
                  >
                    {t(item.labelKey)}
                  </Anchor>
                ))}
              </Group>
            )}
          </Box>

          <Box
            className={classes.column}
            style={{ justifyContent: 'flex-end', gap: '12px' }}
          >
            <Box visibleFrom='md'>{languageSwitch}</Box>
            {withNavigation && (
              <Burger
                opened={drawerOpen}
                onClick={openDrawer}
                hiddenFrom='md'
                size='sm'
                color='white'
                aria-label='Toggle navigation'
              />
            )}
          </Box>
        </Flex>
      </Container>

      <Drawer
        opened={drawerOpen}
        onClose={closeDrawer}
        position='right'
        size='75%'
        hiddenFrom='md'
        withCloseButton
        title={null}
        styles={{
          content: { backgroundColor: 'var(--bg-dark)' },
          header: { backgroundColor: 'var(--bg-dark)' },
        }}
      >
        <Stack gap='lg'>
          <Group component='nav' tt='uppercase' gap='md'>
            <Stack gap='sm' style={{ width: '100%' }}>
              {MENU_ITEMS.map((item) => (
                <Anchor
                  key={item.labelKey}
                  component={Link}
                  to={item.url}
                  onClick={closeDrawer}
                  underline='never'
                  c='white'
                  fz='18px'
                  fw='500'
                >
                  {t(item.labelKey)}
                </Anchor>
              ))}
            </Stack>
          </Group>
          {languageSwitch}
        </Stack>
      </Drawer>
    </header>
  );
}
